version: "3.1"

services:
  postgres:
    image: postgres:latest
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=gostack_gobarber
      - POSTGRES_PASSWORD=docker
    ports:
      - "5432:5432"
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"


